// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)


genvar board_x, board_y, xx, yy;


//
// Scope: /board_y[0:0]
//

//
// Scope: /board_y/board_x[0:0]
//

//
// Scope: /board_y/board_x/life
//

//
// Scope: /board_y/board_x/life|default
//

// For /board_y/board_x/life|default$reset.
logic BoardY_BoardX_Life_DEFAULT_reset_a1 [0:0][0:0],
      BoardY_BoardX_Life_DEFAULT_reset_a2 [0:0][0:0];

//
// Scope: /board_y/board_x/life|default/tb
//

// For /board_y/board_x/life|default/tb$above_min_start.
logic BoardY_BoardX_Life_DEFAULT_Tb_above_min_start_a2 [0:0][0:0];

// For /board_y/board_x/life|default/tb$alive_cnt.
logic [21:0] BoardY_BoardX_Life_DEFAULT_Tb_alive_cnt_a2 [0:0][0:0];

// For /board_y/board_x/life|default/tb$below_max_stop.
logic BoardY_BoardX_Life_DEFAULT_Tb_below_max_stop_a2 [0:0][0:0];

// For /board_y/board_x/life|default/tb$passed.
logic [0:0] BoardY_BoardX_Life_DEFAULT_Tb_passed_a2 [0:0];

// For /board_y/board_x/life|default/tb$start_ok.
logic BoardY_BoardX_Life_DEFAULT_Tb_start_ok_a2 [0:0][0:0],
      BoardY_BoardX_Life_DEFAULT_Tb_start_ok_a3 [0:0][0:0];

// For /board_y/board_x/life|default/tb$stop_cnt.
logic [7:0] BoardY_BoardX_Life_DEFAULT_Tb_stop_cnt_a2 [0:0][0:0],
            BoardY_BoardX_Life_DEFAULT_Tb_stop_cnt_a3 [0:0][0:0];

//
// Scope: /board_y/board_x/life|default/tb/yy[9:0]
//

// For /board_y/board_x/life|default/tb/yy$below_alive_accum.
logic [21:0] BoardY_BoardX_Life_DEFAULT_Tb_Yy_below_alive_accum_a2 [0:0][0:0][9:0];

// For /board_y/board_x/life|default/tb/yy$vert_alive_accum.
logic [21:0] BoardY_BoardX_Life_DEFAULT_Tb_Yy_vert_alive_accum_a2 [0:0][0:0][9:0];

//
// Scope: /board_y/board_x/life|default/tb/yy/xx[9:0]
//

// For /board_y/board_x/life|default/tb/yy/xx$horiz_alive_accum.
logic [10:0] BoardY_BoardX_Life_DEFAULT_Tb_Yy_Xx_horiz_alive_accum_a2 [0:0][0:0][9:0][9:0];

// For /board_y/board_x/life|default/tb/yy/xx$right_alive_accum.
logic [10:0] BoardY_BoardX_Life_DEFAULT_Tb_Yy_Xx_right_alive_accum_a2 [0:0][0:0][9:0][9:0];

//
// Scope: /board_y/board_x/life|default/yy[9:0]
//

//
// Scope: /board_y/board_x/life|default/yy/xx[9:0]
//

// For /board_y/board_x/life|default/yy/xx$alive.
logic BoardY_BoardX_Life_DEFAULT_Yy_Xx_alive_a1 [0:0][0:0][9:0][9:0],
      BoardY_BoardX_Life_DEFAULT_Yy_Xx_alive_a2 [0:0][0:0][9:0][9:0];

// For /board_y/board_x/life|default/yy/xx$cnt.
logic [3:0] BoardY_BoardX_Life_DEFAULT_Yy_Xx_cnt_a1 [0:0][0:0][9:0][9:0];

// For /board_y/board_x/life|default/yy/xx$init_alive.
logic [0:0] BoardY_BoardX_Life_DEFAULT_Yy_Xx_init_alive_a1 [0:0][0:0][9:0][9:0];

// For /board_y/board_x/life|default/yy/xx$row_cnt.
logic [1:0] BoardY_BoardX_Life_DEFAULT_Yy_Xx_row_cnt_a1 [0:0][0:0][9:0][9:0];



   //
   // Scope: /board_y[0:0]
   //
   for (board_y = 0; board_y <= 0; board_y++) begin : L1gen_BoardY

      //
      // Scope: /board_x[0:0]
      //
      for (board_x = 0; board_x <= 0; board_x++) begin : L2gen_BoardX

         //
         // Scope: /life
         //


            //
            // Scope: |default
            //

               // Staging of $reset.
               always_ff @(posedge clk) BoardY_BoardX_Life_DEFAULT_reset_a2[board_y][board_x] <= BoardY_BoardX_Life_DEFAULT_reset_a1[board_y][board_x];


               //
               // Scope: /tb
               //

                  // Staging of $start_ok.
                  always_ff @(posedge clk) BoardY_BoardX_Life_DEFAULT_Tb_start_ok_a3[board_y][board_x] <= BoardY_BoardX_Life_DEFAULT_Tb_start_ok_a2[board_y][board_x];

                  // Staging of $stop_cnt.
                  always_ff @(posedge clk) BoardY_BoardX_Life_DEFAULT_Tb_stop_cnt_a3[board_y][board_x][7:0] <= BoardY_BoardX_Life_DEFAULT_Tb_stop_cnt_a2[board_y][board_x][7:0];



               //
               // Scope: /yy[9:0]
               //
               for (yy = 0; yy <= 9; yy++) begin : L3gen_Life_DEFAULT_Yy

                  //
                  // Scope: /xx[9:0]
                  //
                  for (xx = 0; xx <= 9; xx++) begin : L4gen_Xx
                     // Staging of $alive.
                     always_ff @(posedge clk) BoardY_BoardX_Life_DEFAULT_Yy_Xx_alive_a2[board_y][board_x][yy][xx] <= BoardY_BoardX_Life_DEFAULT_Yy_Xx_alive_a1[board_y][board_x][yy][xx];

                  end
               end


      end
   end

