`line 2 "life.tlv" 0 //_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
`line 4 "life.tlv" 1
//_\SV

// --------------------------------------------------------------------
//
// This example implements Conway's Game of Life.
// In this "game", a grid of cells are born and die based on the
// number of live neighbors they have in each step (clock cycle).
// A cell's neighbors are the surrounding 8 cells, which includes the
// diagonals.
//   - A cell is born if exactly 3 neighbors are alive.
//   - A cell dies from overcrowding or starvation if it have >3 or <2
//     neighbors.
//
// Output shows the grid in each step of simulation.
//
// There is support here for multiple boards simulated simultaneously and
// mirrored symmetry.
//
// --------------------------------------------------------------------


module top(input wire clk, input wire reset, input wire [31:0] cyc_cnt, output wire passed, output wire failed);    /* verilator lint_save */ /* verilator lint_off UNOPTFLAT */  bit [256:0] RW_rand_raw; bit [256+63:0] RW_rand_vect; pseudo_rand #(.WIDTH(257)) pseudo_rand (clk, reset, RW_rand_raw[256:0]); assign RW_rand_vect[256+63:0] = {RW_rand_raw[62:0], RW_rand_raw};  /* verilator lint_restore */  /* verilator lint_off WIDTH */ /* verilator lint_off UNOPTFLAT */

// -------------------------
// Parameters

// Board size



/* verilator lint_off UNOPTFLAT */  // To silence Verilator warnings.
`line 163 "life.tlv" 1


// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
`line 0 "life.sv" 1
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)


genvar board_x, board_y, xx, yy;




   //
   // Scope: /board_y[0:0]
   //
   for (board_y = 0; board_y <= 0; board_y++) begin : L1gen_BoardY

      //
      // Scope: /board_x[0:0]
      //
      for (board_x = 0; board_x <= 0; board_x++) begin : L2gen_BoardX

         //
         // Scope: /life
         //


            //
            // Scope: |default
            //

               // Staging of $reset.
               always_ff @(posedge clk) L1_BoardY[board_y].L2_BoardX[board_x].L2_Life_DEFAULT_reset_a2 <= L1_BoardY[board_y].L2_BoardX[board_x].L2_Life_DEFAULT_reset_a1;


               //
               // Scope: /tb
               //

                  // Staging of $start_ok.
                  always_ff @(posedge clk) L1_BoardY[board_y].L2_BoardX[board_x].L2_Life_DEFAULT_Tb_start_ok_a3 <= L1_BoardY[board_y].L2_BoardX[board_x].L2_Life_DEFAULT_Tb_start_ok_a2;

                  // Staging of $stop_cnt.
                  always_ff @(posedge clk) L1_BoardY[board_y].L2_BoardX[board_x].L2_Life_DEFAULT_Tb_stop_cnt_a3[7:0] <= L1_BoardY[board_y].L2_BoardX[board_x].L2_Life_DEFAULT_Tb_stop_cnt_a2[7:0];



               //
               // Scope: /yy[9:0]
               //
               for (yy = 0; yy <= 9; yy++) begin : L3gen_Life_DEFAULT_Yy

                  //
                  // Scope: /xx[9:0]
                  //
                  for (xx = 0; xx <= 9; xx++) begin : L4gen_Xx
                     // Staging of $alive.
                     always_ff @(posedge clk) L1_BoardY[board_y].L2_BoardX[board_x].L3_Life_DEFAULT_Yy[yy].L3_Xx_alive_a2[xx] <= L1_BoardY[board_y].L2_BoardX[board_x].L3_Life_DEFAULT_Yy[yy].L3_Xx_alive_a1[xx];

                  end
               end


      end
   end

// ---------- Generated Code Ends ----------
`line 165 "life.tlv" 2
//_\TLV
   for (board_y = 0; board_y <= 0; board_y++) begin : L1_BoardY logic [0:0] L1_BoardX_Life_DEFAULT_Tb_passed_a2; //_/board_y     // E.g., [2:0] for 3 boards high.
      for (board_x = 0; board_x <= 0; board_x++) begin : L2_BoardX logic L2_Life_DEFAULT_reset_a1, L2_Life_DEFAULT_reset_a2; logic L2_Life_DEFAULT_Tb_above_min_start_a2; logic [21:0] L2_Life_DEFAULT_Tb_alive_cnt_a2; logic L2_Life_DEFAULT_Tb_below_max_stop_a2; logic L2_Life_DEFAULT_Tb_start_ok_a2, L2_Life_DEFAULT_Tb_start_ok_a3; logic [7:0] L2_Life_DEFAULT_Tb_stop_cnt_a2, L2_Life_DEFAULT_Tb_stop_cnt_a3; logic [21:0] L2_Life_DEFAULT_Tb_Yy_vert_alive_accum_a2 [9:0]; logic [1:0] L2_Life_DEFAULT_Yy_Xx_row_cnt_a1 [9:0][9:0]; //_/board_x  // E.g., [2:0] for 3 boards across.
         /* Viz omitted here */

         //m5+snowflake_init()   // Uncomment to enable "snowflake" symmetry.
         `line 55 "life.tlv" 1   // Instantiated from life.tlv, 171 as: m5+life(/life, )
            //_/life
               /* Viz omitted here */


               //_|default
         
         
                  // ======
                  // Design
                  // ======
         
                  //_@1
                     assign L2_Life_DEFAULT_reset_a1 = reset;
                     for (yy = 0; yy <= 9; yy++) begin : L3_Life_DEFAULT_Yy logic L3_Xx_alive_a1 [9:0], L3_Xx_alive_a2 [9:0]; //_/yy
                        for (xx = 0; xx <= 9; xx++) begin : L4_Xx logic [3:0] L4_cnt_a1; logic [0:0] L4_init_alive_a1; //_/xx
                           // Cell logic
         
                           // -----------
                           // Population count ($cnt) of 3x3 square (with edge logic).
         
                           // Sum left + me + right.
                           assign L2_Life_DEFAULT_Yy_Xx_row_cnt_a1[yy][xx][1:0] = {1'b0, (L3_Xx_alive_a2[(xx + 10-1) % 10] & (xx > 0))} +
                                           {1'b0, L3_Xx_alive_a2[xx]} +
                                           {1'b0, (L3_Xx_alive_a2[(xx + 1) % 10] & (xx < 10-1))};
                           // Sum three $row_cnt's: above + mine + below.
                           assign L4_cnt_a1[3:0] = {2'b00, (L2_Life_DEFAULT_Yy_Xx_row_cnt_a1[(yy + 10-1) % 10][xx] & {2{(yy > 0)}})} +
                                       {2'b00, L2_Life_DEFAULT_Yy_Xx_row_cnt_a1[yy][xx][1:0]} +
                                       {2'b00, (L2_Life_DEFAULT_Yy_Xx_row_cnt_a1[(yy + 1) % 10][xx] & {2{(yy < 10-1)}})};
         
         
                           // ----------
                           // Init state
         
                           assign L4_init_alive_a1[0:0] = RW_rand_vect[(0 + ((yy * xx) ^ ((3 * xx) + yy))) % 257 +: 1];
         
         
                           // -----------
                           // Am I alive?
         
                           assign L3_Xx_alive_a1[xx] = L2_Life_DEFAULT_reset_a1 ? L4_init_alive_a1 :           // init
                                    L3_Xx_alive_a2[xx] ? (L4_cnt_a1 >= 3 && L4_cnt_a1 <= 4) :   // stay alive
                                                (L4_cnt_a1 == 3); end end                 // born
         
         
                  // ==================
                  // Embedded Testbench
                  // ==================
                  //
                  // Declare success when total live cells was above 25% and remains below 6.25% for 20 cycles.
         
                  // Count live cells through accumulation, into $alive_cnt.
                  // Accumulate right-to-left, then bottom-to-top through >yy[0].
                  //_/tb
                     //_@2
                        for (yy = 0; yy <= 9; yy++) begin : L3_Life_DEFAULT_Tb_Yy logic [21:0] L3_below_alive_accum_a2; logic [10:0] L3_Xx_horiz_alive_accum_a2 [9:0]; //_/yy
                           for (xx = 0; xx <= 9; xx++) begin : L4_Xx logic [10:0] L4_right_alive_accum_a2; //_/xx
                              assign L4_right_alive_accum_a2[10:0] = (xx < 9) ? L3_Xx_horiz_alive_accum_a2[xx + 1] : 11'b0;
                              assign L3_Xx_horiz_alive_accum_a2[xx][10:0] = L4_right_alive_accum_a2 + {10'b0, L3_Life_DEFAULT_Yy[yy].L3_Xx_alive_a2[xx]}; end
                           assign L3_below_alive_accum_a2[21:0] = (yy < 9) ? L2_Life_DEFAULT_Tb_Yy_vert_alive_accum_a2[yy + 1] : 22'b0;
                           assign L2_Life_DEFAULT_Tb_Yy_vert_alive_accum_a2[yy][21:0] = L3_below_alive_accum_a2 + {11'b0, L3_Xx_horiz_alive_accum_a2[0]}; end
                        assign L2_Life_DEFAULT_Tb_alive_cnt_a2[21:0] = L2_Life_DEFAULT_Tb_Yy_vert_alive_accum_a2[0];
                        assign L2_Life_DEFAULT_Tb_above_min_start_a2 = L2_Life_DEFAULT_Tb_alive_cnt_a2 > (10 * 10) >> 2;  // 1/4
                        assign L2_Life_DEFAULT_Tb_below_max_stop_a2  = L2_Life_DEFAULT_Tb_alive_cnt_a2 < (10 * 10) >> 4;  // 1/16
                        assign L2_Life_DEFAULT_Tb_start_ok_a2 = L2_Life_DEFAULT_reset_a2 ? 1'b0 : (L2_Life_DEFAULT_Tb_start_ok_a3 || L2_Life_DEFAULT_Tb_above_min_start_a2);
                        assign L2_Life_DEFAULT_Tb_stop_cnt_a2[7:0] = L2_Life_DEFAULT_reset_a2  ? 8'b0 :
                                         L2_Life_DEFAULT_Tb_below_max_stop_a2 ? L2_Life_DEFAULT_Tb_stop_cnt_a3 + 8'b1 :
                                                           8'b0;
                        assign L1_BoardX_Life_DEFAULT_Tb_passed_a2[board_x] = L2_Life_DEFAULT_Tb_start_ok_a3 && ((L2_Life_DEFAULT_Tb_alive_cnt_a2 == '0) || (L2_Life_DEFAULT_Tb_stop_cnt_a3 > 8'd20));
         
         
                  // ===
                  // VIZ
                  // ===
                  //_@1
                     for (yy = 0; yy <= 9; yy++) begin : L3b_Life_DEFAULT_Yy //_/yy
                        /* Viz omitted here */









                        for (xx = 0; xx <= 9; xx++) begin : L4b_Xx //_/xx
                           /* Viz omitted here */




















                           end end
         end end //_\end_source
         `line 172 "life.tlv" 2
   //_|tb
      //_@2
         // Determine passed by looking at top boards only.
         assign passed = | L1_BoardY[0].L1_BoardX_Life_DEFAULT_Tb_passed_a2;

//_\SV
endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
