`line 2 "life.tlv" 0 //_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
`line 4 "life.tlv" 1
//_\SV

// --------------------------------------------------------------------
//
// This example implements Conway's Game of Life.
// In this "game", a grid of cells are born and die based on the
// number of live neighbors they have in each step (clock cycle).
// A cell's neighbors are the surrounding 8 cells, which includes the
// diagonals.
//   - A cell is born if exactly 3 neighbors are alive.
//   - A cell dies from overcrowding or starvation if it have >3 or <2
//     neighbors.
//
// Output shows the grid in each step of simulation.
//
// There is support here for multiple boards simulated simultaneously and
// mirrored symmetry.
//
// --------------------------------------------------------------------


module top(input wire clk, input wire reset, input wire [31:0] cyc_cnt, output wire passed, output wire failed);    /* verilator lint_save */ /* verilator lint_off UNOPTFLAT */  bit [256:0] RW_rand_raw; bit [256+63:0] RW_rand_vect; pseudo_rand #(.WIDTH(257)) pseudo_rand (clk, reset, RW_rand_raw[256:0]); assign RW_rand_vect[256+63:0] = {RW_rand_raw[62:0], RW_rand_raw};  /* verilator lint_restore */  /* verilator lint_off WIDTH */ /* verilator lint_off UNOPTFLAT */

// -------------------------
// Parameters

// Board size



/* verilator lint_off UNOPTFLAT */  // To silence Verilator warnings.
`line 163 "life.tlv" 1


`include "life_flat_gen.sv" //_\TLV
   for (board_y = 0; board_y <= 0; board_y++) begin : L1_BoardY //_/board_y     // E.g., [2:0] for 3 boards high.
      for (board_x = 0; board_x <= 0; board_x++) begin : L2_BoardX //_/board_x  // E.g., [2:0] for 3 boards across.
         /* Viz omitted here */

         //m5+snowflake_init()   // Uncomment to enable "snowflake" symmetry.
         `line 55 "life.tlv" 1   // Instantiated from life.tlv, 171 as: m5+life(/life, )
            //_/life
               /* Viz omitted here */


               //_|default
         
         
                  // ======
                  // Design
                  // ======
         
                  //_@1
                     assign BoardY_BoardX_Life_DEFAULT_reset_a1[board_y][board_x] = reset;
                     for (yy = 0; yy <= 9; yy++) begin : L3_Life_DEFAULT_Yy //_/yy
                        for (xx = 0; xx <= 9; xx++) begin : L4_Xx //_/xx
                           // Cell logic
         
                           // -----------
                           // Population count ($cnt) of 3x3 square (with edge logic).
         
                           // Sum left + me + right.
                           assign BoardY_BoardX_Life_DEFAULT_Yy_Xx_row_cnt_a1[board_y][board_x][yy][xx][1:0] = {1'b0, (BoardY_BoardX_Life_DEFAULT_Yy_Xx_alive_a2[board_y][board_x][yy][(xx + 10-1) % 10] & (xx > 0))} +
                                           {1'b0, BoardY_BoardX_Life_DEFAULT_Yy_Xx_alive_a2[board_y][board_x][yy][xx]} +
                                           {1'b0, (BoardY_BoardX_Life_DEFAULT_Yy_Xx_alive_a2[board_y][board_x][yy][(xx + 1) % 10] & (xx < 10-1))};
                           // Sum three $row_cnt's: above + mine + below.
                           assign BoardY_BoardX_Life_DEFAULT_Yy_Xx_cnt_a1[board_y][board_x][yy][xx][3:0] = {2'b00, (BoardY_BoardX_Life_DEFAULT_Yy_Xx_row_cnt_a1[board_y][board_x][(yy + 10-1) % 10][xx] & {2{(yy > 0)}})} +
                                       {2'b00, BoardY_BoardX_Life_DEFAULT_Yy_Xx_row_cnt_a1[board_y][board_x][yy][xx][1:0]} +
                                       {2'b00, (BoardY_BoardX_Life_DEFAULT_Yy_Xx_row_cnt_a1[board_y][board_x][(yy + 1) % 10][xx] & {2{(yy < 10-1)}})};
         
         
                           // ----------
                           // Init state
         
                           assign BoardY_BoardX_Life_DEFAULT_Yy_Xx_init_alive_a1[board_y][board_x][yy][xx][0:0] = RW_rand_vect[(0 + ((yy * xx) ^ ((3 * xx) + yy))) % 257 +: 1];
         
         
                           // -----------
                           // Am I alive?
         
                           assign BoardY_BoardX_Life_DEFAULT_Yy_Xx_alive_a1[board_y][board_x][yy][xx] = BoardY_BoardX_Life_DEFAULT_reset_a1[board_y][board_x] ? BoardY_BoardX_Life_DEFAULT_Yy_Xx_init_alive_a1[board_y][board_x][yy][xx] :           // init
                                    BoardY_BoardX_Life_DEFAULT_Yy_Xx_alive_a2[board_y][board_x][yy][xx] ? (BoardY_BoardX_Life_DEFAULT_Yy_Xx_cnt_a1[board_y][board_x][yy][xx] >= 3 && BoardY_BoardX_Life_DEFAULT_Yy_Xx_cnt_a1[board_y][board_x][yy][xx] <= 4) :   // stay alive
                                                (BoardY_BoardX_Life_DEFAULT_Yy_Xx_cnt_a1[board_y][board_x][yy][xx] == 3); end end                 // born
         
         
                  // ==================
                  // Embedded Testbench
                  // ==================
                  //
                  // Declare success when total live cells was above 25% and remains below 6.25% for 20 cycles.
         
                  // Count live cells through accumulation, into $alive_cnt.
                  // Accumulate right-to-left, then bottom-to-top through >yy[0].
                  //_/tb
                     //_@2
                        for (yy = 0; yy <= 9; yy++) begin : L3_Life_DEFAULT_Tb_Yy //_/yy
                           for (xx = 0; xx <= 9; xx++) begin : L4_Xx //_/xx
                              assign BoardY_BoardX_Life_DEFAULT_Tb_Yy_Xx_right_alive_accum_a2[board_y][board_x][yy][xx][10:0] = (xx < 9) ? BoardY_BoardX_Life_DEFAULT_Tb_Yy_Xx_horiz_alive_accum_a2[board_y][board_x][yy][xx + 1] : 11'b0;
                              assign BoardY_BoardX_Life_DEFAULT_Tb_Yy_Xx_horiz_alive_accum_a2[board_y][board_x][yy][xx][10:0] = BoardY_BoardX_Life_DEFAULT_Tb_Yy_Xx_right_alive_accum_a2[board_y][board_x][yy][xx] + {10'b0, BoardY_BoardX_Life_DEFAULT_Yy_Xx_alive_a2[board_y][board_x][yy][xx]}; end
                           assign BoardY_BoardX_Life_DEFAULT_Tb_Yy_below_alive_accum_a2[board_y][board_x][yy][21:0] = (yy < 9) ? BoardY_BoardX_Life_DEFAULT_Tb_Yy_vert_alive_accum_a2[board_y][board_x][yy + 1] : 22'b0;
                           assign BoardY_BoardX_Life_DEFAULT_Tb_Yy_vert_alive_accum_a2[board_y][board_x][yy][21:0] = BoardY_BoardX_Life_DEFAULT_Tb_Yy_below_alive_accum_a2[board_y][board_x][yy] + {11'b0, BoardY_BoardX_Life_DEFAULT_Tb_Yy_Xx_horiz_alive_accum_a2[board_y][board_x][yy][0]}; end
                        assign BoardY_BoardX_Life_DEFAULT_Tb_alive_cnt_a2[board_y][board_x][21:0] = BoardY_BoardX_Life_DEFAULT_Tb_Yy_vert_alive_accum_a2[board_y][board_x][0];
                        assign BoardY_BoardX_Life_DEFAULT_Tb_above_min_start_a2[board_y][board_x] = BoardY_BoardX_Life_DEFAULT_Tb_alive_cnt_a2[board_y][board_x] > (10 * 10) >> 2;  // 1/4
                        assign BoardY_BoardX_Life_DEFAULT_Tb_below_max_stop_a2[board_y][board_x]  = BoardY_BoardX_Life_DEFAULT_Tb_alive_cnt_a2[board_y][board_x] < (10 * 10) >> 4;  // 1/16
                        assign BoardY_BoardX_Life_DEFAULT_Tb_start_ok_a2[board_y][board_x] = BoardY_BoardX_Life_DEFAULT_reset_a2[board_y][board_x] ? 1'b0 : (BoardY_BoardX_Life_DEFAULT_Tb_start_ok_a3[board_y][board_x] || BoardY_BoardX_Life_DEFAULT_Tb_above_min_start_a2[board_y][board_x]);
                        assign BoardY_BoardX_Life_DEFAULT_Tb_stop_cnt_a2[board_y][board_x][7:0] = BoardY_BoardX_Life_DEFAULT_reset_a2[board_y][board_x]  ? 8'b0 :
                                         BoardY_BoardX_Life_DEFAULT_Tb_below_max_stop_a2[board_y][board_x] ? BoardY_BoardX_Life_DEFAULT_Tb_stop_cnt_a3[board_y][board_x] + 8'b1 :
                                                           8'b0;
                        assign BoardY_BoardX_Life_DEFAULT_Tb_passed_a2[board_y][board_x] = BoardY_BoardX_Life_DEFAULT_Tb_start_ok_a3[board_y][board_x] && ((BoardY_BoardX_Life_DEFAULT_Tb_alive_cnt_a2[board_y][board_x] == '0) || (BoardY_BoardX_Life_DEFAULT_Tb_stop_cnt_a3[board_y][board_x] > 8'd20));
         
         
                  // ===
                  // VIZ
                  // ===
                  //_@1
                     for (yy = 0; yy <= 9; yy++) begin : L3b_Life_DEFAULT_Yy //_/yy
                        /* Viz omitted here */









                        for (xx = 0; xx <= 9; xx++) begin : L4b_Xx //_/xx
                           /* Viz omitted here */




















                           end end
         end end //_\end_source
         `line 172 "life.tlv" 2
   //_|tb
      //_@2
         // Determine passed by looking at top boards only.
         assign passed = | BoardY_BoardX_Life_DEFAULT_Tb_passed_a2[0];

//_\SV
endmodule


// Undefine macros defined by SandPiper (in "life_flat_gen.sv").
`undef BOGUS_USE
