/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

module pythagoras(clk, a_in, b_in, cc_sq_out);
  wire \CALC_aa_a1[0] ;
  wire \CALC_aa_a1[1] ;
  wire \CALC_aa_a1[2] ;
  wire \CALC_aa_a1[3] ;
  wire \CALC_aa_sq_a1[0] ;
  wire \CALC_aa_sq_a1[1] ;
  wire \CALC_aa_sq_a1[2] ;
  wire \CALC_aa_sq_a1[3] ;
  wire \CALC_aa_sq_a1[4] ;
  wire \CALC_aa_sq_a1[5] ;
  wire \CALC_aa_sq_a1[6] ;
  wire \CALC_aa_sq_a1[7] ;
  wire \CALC_aa_sq_a2[0] ;
  wire \CALC_aa_sq_a2[1] ;
  wire \CALC_aa_sq_a2[2] ;
  wire \CALC_aa_sq_a2[3] ;
  wire \CALC_aa_sq_a2[4] ;
  wire \CALC_aa_sq_a2[5] ;
  wire \CALC_aa_sq_a2[6] ;
  wire \CALC_aa_sq_a2[7] ;
  wire \CALC_bb_a1[0] ;
  wire \CALC_bb_a1[1] ;
  wire \CALC_bb_a1[2] ;
  wire \CALC_bb_a1[3] ;
  wire \CALC_bb_sq_a1[0] ;
  wire \CALC_bb_sq_a1[1] ;
  wire \CALC_bb_sq_a1[2] ;
  wire \CALC_bb_sq_a1[3] ;
  wire \CALC_bb_sq_a1[4] ;
  wire \CALC_bb_sq_a1[5] ;
  wire \CALC_bb_sq_a1[6] ;
  wire \CALC_bb_sq_a1[7] ;
  wire \CALC_bb_sq_a2[0] ;
  wire \CALC_bb_sq_a2[1] ;
  wire \CALC_bb_sq_a2[2] ;
  wire \CALC_bb_sq_a2[3] ;
  wire \CALC_bb_sq_a2[4] ;
  wire \CALC_bb_sq_a2[5] ;
  wire \CALC_bb_sq_a2[6] ;
  wire \CALC_bb_sq_a2[7] ;
  wire \CALC_cc_sq_a2[0] ;
  wire \CALC_cc_sq_a2[1] ;
  wire \CALC_cc_sq_a2[2] ;
  wire \CALC_cc_sq_a2[3] ;
  wire \CALC_cc_sq_a2[4] ;
  wire \CALC_cc_sq_a2[5] ;
  wire \CALC_cc_sq_a2[6] ;
  wire \CALC_cc_sq_a2[7] ;
  wire \CALC_cc_sq_a2[8] ;
  input [3:0] a_in;
  wire [3:0] a_in;
  input [3:0] b_in;
  wire [3:0] b_in;
  output [8:0] cc_sq_out;
  wire [8:0] cc_sq_out;
  input clk;
  wire clk;
  assign cc_sq_out = { \CALC_aa_sq_a2[7] , \CALC_aa_sq_a2[6] , \CALC_aa_sq_a2[5] , \CALC_aa_sq_a2[4] , \CALC_aa_sq_a2[3] , \CALC_aa_sq_a2[2] , \CALC_aa_sq_a2[1] , \CALC_aa_sq_a2[0]  } + { \CALC_bb_sq_a2[7] , \CALC_bb_sq_a2[6] , \CALC_bb_sq_a2[5] , \CALC_bb_sq_a2[4] , \CALC_bb_sq_a2[3] , \CALC_bb_sq_a2[2] , \CALC_bb_sq_a2[1] , \CALC_bb_sq_a2[0]  };
  reg [7:0] _1_;
  always @(posedge clk)
    _1_ <= { \CALC_bb_sq_a1[7] , \CALC_bb_sq_a1[6] , \CALC_bb_sq_a1[5] , \CALC_bb_sq_a1[4] , \CALC_bb_sq_a1[3] , \CALC_bb_sq_a1[2] , \CALC_bb_sq_a1[1] , \CALC_bb_sq_a1[0]  };
  assign { \CALC_bb_sq_a2[7] , \CALC_bb_sq_a2[6] , \CALC_bb_sq_a2[5] , \CALC_bb_sq_a2[4] , \CALC_bb_sq_a2[3] , \CALC_bb_sq_a2[2] , \CALC_bb_sq_a2[1] , \CALC_bb_sq_a2[0]  } = _1_;
  reg [7:0] _2_;
  always @(posedge clk)
    _2_ <= { \CALC_aa_sq_a1[7] , \CALC_aa_sq_a1[6] , \CALC_aa_sq_a1[5] , \CALC_aa_sq_a1[4] , \CALC_aa_sq_a1[3] , \CALC_aa_sq_a1[2] , \CALC_aa_sq_a1[1] , \CALC_aa_sq_a1[0]  };
  assign { \CALC_aa_sq_a2[7] , \CALC_aa_sq_a2[6] , \CALC_aa_sq_a2[5] , \CALC_aa_sq_a2[4] , \CALC_aa_sq_a2[3] , \CALC_aa_sq_a2[2] , \CALC_aa_sq_a2[1] , \CALC_aa_sq_a2[0]  } = _2_;
  stage_0 stage_0 (
    .\CALC_aa_sq_a1[0] (\CALC_aa_sq_a1[0] ),
    .\CALC_aa_sq_a1[1] (\CALC_aa_sq_a1[1] ),
    .\CALC_aa_sq_a1[2] (\CALC_aa_sq_a1[2] ),
    .\CALC_aa_sq_a1[3] (\CALC_aa_sq_a1[3] ),
    .\CALC_aa_sq_a1[4] (\CALC_aa_sq_a1[4] ),
    .\CALC_aa_sq_a1[5] (\CALC_aa_sq_a1[5] ),
    .\CALC_aa_sq_a1[6] (\CALC_aa_sq_a1[6] ),
    .\CALC_aa_sq_a1[7] (\CALC_aa_sq_a1[7] ),
    .\CALC_bb_sq_a1[0] (\CALC_bb_sq_a1[0] ),
    .\CALC_bb_sq_a1[1] (\CALC_bb_sq_a1[1] ),
    .\CALC_bb_sq_a1[2] (\CALC_bb_sq_a1[2] ),
    .\CALC_bb_sq_a1[3] (\CALC_bb_sq_a1[3] ),
    .\CALC_bb_sq_a1[4] (\CALC_bb_sq_a1[4] ),
    .\CALC_bb_sq_a1[5] (\CALC_bb_sq_a1[5] ),
    .\CALC_bb_sq_a1[6] (\CALC_bb_sq_a1[6] ),
    .\CALC_bb_sq_a1[7] (\CALC_bb_sq_a1[7] ),
    .a_in(a_in),
    .b_in(b_in)
  );
  assign \CALC_aa_a1[0]  = a_in[0];
  assign \CALC_aa_a1[1]  = a_in[1];
  assign \CALC_aa_a1[2]  = a_in[2];
  assign \CALC_aa_a1[3]  = a_in[3];
  assign \CALC_bb_a1[0]  = b_in[0];
  assign \CALC_bb_a1[1]  = b_in[1];
  assign \CALC_bb_a1[2]  = b_in[2];
  assign \CALC_bb_a1[3]  = b_in[3];
  assign \CALC_cc_sq_a2[0]  = cc_sq_out[0];
  assign \CALC_cc_sq_a2[1]  = cc_sq_out[1];
  assign \CALC_cc_sq_a2[2]  = cc_sq_out[2];
  assign \CALC_cc_sq_a2[3]  = cc_sq_out[3];
  assign \CALC_cc_sq_a2[4]  = cc_sq_out[4];
  assign \CALC_cc_sq_a2[5]  = cc_sq_out[5];
  assign \CALC_cc_sq_a2[6]  = cc_sq_out[6];
  assign \CALC_cc_sq_a2[7]  = cc_sq_out[7];
  assign \CALC_cc_sq_a2[8]  = cc_sq_out[8];
endmodule

module stage_0(a_in, b_in, \CALC_aa_sq_a1[0] , \CALC_aa_sq_a1[1] , \CALC_aa_sq_a1[2] , \CALC_aa_sq_a1[3] , \CALC_aa_sq_a1[4] , \CALC_aa_sq_a1[5] , \CALC_aa_sq_a1[6] , \CALC_aa_sq_a1[7] , \CALC_bb_sq_a1[0] , \CALC_bb_sq_a1[1] , \CALC_bb_sq_a1[2] , \CALC_bb_sq_a1[3] , \CALC_bb_sq_a1[4] , \CALC_bb_sq_a1[5] , \CALC_bb_sq_a1[6] , \CALC_bb_sq_a1[7] );
  output \CALC_aa_sq_a1[0] ;
  wire \CALC_aa_sq_a1[0] ;
  output \CALC_aa_sq_a1[1] ;
  wire \CALC_aa_sq_a1[1] ;
  output \CALC_aa_sq_a1[2] ;
  wire \CALC_aa_sq_a1[2] ;
  output \CALC_aa_sq_a1[3] ;
  wire \CALC_aa_sq_a1[3] ;
  output \CALC_aa_sq_a1[4] ;
  wire \CALC_aa_sq_a1[4] ;
  output \CALC_aa_sq_a1[5] ;
  wire \CALC_aa_sq_a1[5] ;
  output \CALC_aa_sq_a1[6] ;
  wire \CALC_aa_sq_a1[6] ;
  output \CALC_aa_sq_a1[7] ;
  wire \CALC_aa_sq_a1[7] ;
  output \CALC_bb_sq_a1[0] ;
  wire \CALC_bb_sq_a1[0] ;
  output \CALC_bb_sq_a1[1] ;
  wire \CALC_bb_sq_a1[1] ;
  output \CALC_bb_sq_a1[2] ;
  wire \CALC_bb_sq_a1[2] ;
  output \CALC_bb_sq_a1[3] ;
  wire \CALC_bb_sq_a1[3] ;
  output \CALC_bb_sq_a1[4] ;
  wire \CALC_bb_sq_a1[4] ;
  output \CALC_bb_sq_a1[5] ;
  wire \CALC_bb_sq_a1[5] ;
  output \CALC_bb_sq_a1[6] ;
  wire \CALC_bb_sq_a1[6] ;
  output \CALC_bb_sq_a1[7] ;
  wire \CALC_bb_sq_a1[7] ;
  input [3:0] a_in;
  wire [3:0] a_in;
  input [3:0] b_in;
  wire [3:0] b_in;
  assign { \CALC_aa_sq_a1[7] , \CALC_aa_sq_a1[6] , \CALC_aa_sq_a1[5] , \CALC_aa_sq_a1[4] , \CALC_aa_sq_a1[3] , \CALC_aa_sq_a1[2] , \CALC_aa_sq_a1[1] , \CALC_aa_sq_a1[0]  } = a_in ** $signed(32'd2);
  assign { \CALC_bb_sq_a1[7] , \CALC_bb_sq_a1[6] , \CALC_bb_sq_a1[5] , \CALC_bb_sq_a1[4] , \CALC_bb_sq_a1[3] , \CALC_bb_sq_a1[2] , \CALC_bb_sq_a1[1] , \CALC_bb_sq_a1[0]  } = b_in ** $signed(32'd2);
endmodule
