`line 2 "ripple.tlv" 0 //_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
`line 18 "ripple.tlv" 1

//_\SV
   // The main module (as required for Makerchip).
   module top(input wire clk, input wire reset, input wire [31:0] cyc_cnt, output wire passed, output wire failed);    /* verilator lint_save */ /* verilator lint_off UNOPTFLAT */  bit [256:0] RW_rand_raw; bit [256+63:0] RW_rand_vect; pseudo_rand #(.WIDTH(257)) pseudo_rand (clk, reset, RW_rand_raw[256:0]); assign RW_rand_vect[256+63:0] = {RW_rand_raw[62:0], RW_rand_raw};  /* verilator lint_restore */  /* verilator lint_off WIDTH */ /* verilator lint_off UNOPTFLAT */
`include "ripple_gen.sv" //_\TLV
   // Instantiate an 8-bit ripple-carry adder, connecting input and output bits to vector signals.

     // addend MSB bit index
   // Inputs
   assign L0_addend1_a0[7:0] = RW_rand_vect[(0 + (0)) % 257 +: 8];
   assign L0_addend2_a0[7:0] = RW_rand_vect[(124 + (0)) % 257 +: 8];
   // Connect inputs
   for (slice = 0; slice <= 7; slice++) begin : L1_Slice logic L1_in1_a0; logic L1_in2_a0; //_/slice
      assign L1_in1_a0 = L0_addend1_a0[slice];
      assign L1_in2_a0 = L0_addend2_a0[slice]; end
   // Adder
   `line 15 "ripple.tlv" 1   // Instantiated from ripple.tlv, 34 as: m5+ripple_carry_adder(/slice, m5_get(msb), $out, $carry_out, $in1, $in2)
      for (slice = 0; slice <= 7; slice++) begin : L1b_Slice logic L1_carry_in_a0; //_/slice
         assign L1_carry_in_a0 = (slice == 0) ? 1'b0 : Slice_carry_out_a0[(slice - 1) % (7 + 1)];
         `line 9 "ripple.tlv" 1   // Instantiated from ripple.tlv, 17 as: m5+full_adder($out, $carry_out, $in1, $in2, $carry_in)
            assign Slice_out_a0[slice] = L1_Slice[slice].L1_in1_a0 ^ L1_Slice[slice].L1_in2_a0 ^ L1_carry_in_a0;
            assign Slice_carry_out_a0[slice] = (L1_Slice[slice].L1_in1_a0 + L1_Slice[slice].L1_in2_a0 + L1_carry_in_a0) > 2'b1;
         end //_\end_source
         `line 18 "ripple.tlv" 2
   //_\end_source
   `line 35 "ripple.tlv" 2
   // Outputs
   assign L0_result_a0[8:0] = {Slice_carry_out_a0[7], Slice_out_a0};

   // VIZ
   /* Viz omitted here */






//_\SV
   endmodule


// Undefine macros defined by SandPiper (in "ripple_gen.sv").
`undef BOGUS_USE
