`line 2 "pythagoras.tlv" 0 //_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\SV
   module pythagoras(input wire clk,
                     input wire [3:0] a_in,
                     input wire [3:0] b_in,
                     output wire [8:0] cc_sq_out);
// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
`line 0 "pythagoras.sv" 1
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |calc$aa.
logic [3:0] CALC_aa_a1;

// For |calc$aa_sq.
logic [7:0] CALC_aa_sq_a1,
            CALC_aa_sq_a2;

// For |calc$bb.
logic [3:0] CALC_bb_a1;

// For |calc$bb_sq.
logic [7:0] CALC_bb_sq_a1,
            CALC_bb_sq_a2;

// For |calc$cc_sq.
logic [8:0] CALC_cc_sq_a2;




   //
   // Scope: |calc
   //

      // Staging of $aa_sq.
      always_ff @(posedge clk) CALC_aa_sq_a2[7:0] <= CALC_aa_sq_a1[7:0];

      // Staging of $bb_sq.
      always_ff @(posedge clk) CALC_bb_sq_a2[7:0] <= CALC_bb_sq_a1[7:0];



// ---------- Generated Code Ends ----------
`line 9 "pythagoras.tlv" 2
//_\TLV
   //_|calc
      //_@1
         assign CALC_aa_a1[3:0] = a_in;
         assign CALC_bb_a1[3:0] = b_in;
         assign CALC_aa_sq_a1[7:0] = CALC_aa_a1 ** 2;
         assign CALC_bb_sq_a1[7:0] = CALC_bb_a1 ** 2;
      //_@2
         assign CALC_cc_sq_a2[8:0] = CALC_aa_sq_a2 + CALC_bb_sq_a2;
         assign cc_sq_out = CALC_cc_sq_a2;
//_\SV
   endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
