/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

module pythagoras(clk, a_in, b_in, cc_sq_out);
  wire [3:0] CALC_aa_a1;
  wire [7:0] CALC_aa_sq_a1;
  wire [7:0] CALC_aa_sq_a2;
  wire [3:0] CALC_bb_a1;
  wire [7:0] CALC_bb_sq_a1;
  wire [7:0] CALC_bb_sq_a2;
  wire [8:0] CALC_cc_sq_a2;
  input [3:0] a_in;
  wire [3:0] a_in;
  input [3:0] b_in;
  wire [3:0] b_in;
  output [8:0] cc_sq_out;
  wire [8:0] cc_sq_out;
  input clk;
  wire clk;
  stage1 stage1 (
    .CALC_aa_sq_a1(CALC_aa_sq_a1),
    .CALC_bb_sq_a1(CALC_bb_sq_a1),
    .a_in(a_in),
    .b_in(b_in)
  );
  stage2 stage2 (
    .CALC_aa_sq_a1(CALC_aa_sq_a1),
    .CALC_bb_sq_a1(CALC_bb_sq_a1),
    .cc_sq_out(cc_sq_out),
    .clk(clk)
  );
  assign CALC_aa_a1 = a_in;
  assign CALC_bb_a1 = b_in;
  assign CALC_cc_sq_a2 = cc_sq_out;
endmodule

module stage1(a_in, b_in, CALC_aa_sq_a1, CALC_bb_sq_a1);
  output [7:0] CALC_aa_sq_a1;
  wire [7:0] CALC_aa_sq_a1;
  output [7:0] CALC_bb_sq_a1;
  wire [7:0] CALC_bb_sq_a1;
  input [3:0] a_in;
  wire [3:0] a_in;
  input [3:0] b_in;
  wire [3:0] b_in;
  assign CALC_aa_sq_a1 = a_in ** $signed(32'd2);
  assign CALC_bb_sq_a1 = b_in ** $signed(32'd2);
endmodule

module stage2(clk, cc_sq_out, CALC_aa_sq_a1, CALC_bb_sq_a1);
  input [7:0] CALC_aa_sq_a1;
  wire [7:0] CALC_aa_sq_a1;
  reg [7:0] CALC_aa_sq_a2;
  input [7:0] CALC_bb_sq_a1;
  wire [7:0] CALC_bb_sq_a1;
  reg [7:0] CALC_bb_sq_a2;
  output [8:0] cc_sq_out;
  wire [8:0] cc_sq_out;
  input clk;
  wire clk;
  assign cc_sq_out = CALC_aa_sq_a2 + CALC_bb_sq_a2;
  always @(posedge clk)
    CALC_bb_sq_a2 <= CALC_bb_sq_a1;
  always @(posedge clk)
    CALC_aa_sq_a2 <= CALC_aa_sq_a1;
endmodule
