// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)


genvar slice;


//
// Signals declared top-level.
//

// For $addend1.
logic [7:0] L0_addend1_a0;

// For $addend2.
logic [7:0] L0_addend2_a0;

// For $result.
logic [8:0] L0_result_a0;

// For /slice$carry_out.
logic Slice_carry_out_a0 [7:0];

// For /slice$out.
logic [7:0] Slice_out_a0;


