/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

module fa_0(\L1_Slice[0].L1_in1_a0 , \L1_Slice[0].L1_in2_a0 , \L1b_Slice[1].L1_carry_in_a0 );
  wire [1:0] _0_;
  wire [1:0] _1_;
  input \L1_Slice[0].L1_in1_a0 ;
  wire \L1_Slice[0].L1_in1_a0 ;
  input \L1_Slice[0].L1_in2_a0 ;
  wire \L1_Slice[0].L1_in2_a0 ;
  output \L1b_Slice[1].L1_carry_in_a0 ;
  wire \L1b_Slice[1].L1_carry_in_a0 ;
  assign _0_ = \L1_Slice[0].L1_in1_a0  + \L1_Slice[0].L1_in2_a0 ;
  assign _1_ = + _0_;
  assign \L1b_Slice[1].L1_carry_in_a0  = _1_ > 2'h1;
endmodule

module fa_1(\L1_Slice[1].L1_in1_a0 , \L1_Slice[1].L1_in2_a0 , \L1b_Slice[1].L1_carry_in_a0 , \L1b_Slice[2].L1_carry_in_a0 );
  wire [1:0] _0_;
  wire [1:0] _1_;
  input \L1_Slice[1].L1_in1_a0 ;
  wire \L1_Slice[1].L1_in1_a0 ;
  input \L1_Slice[1].L1_in2_a0 ;
  wire \L1_Slice[1].L1_in2_a0 ;
  input \L1b_Slice[1].L1_carry_in_a0 ;
  wire \L1b_Slice[1].L1_carry_in_a0 ;
  output \L1b_Slice[2].L1_carry_in_a0 ;
  wire \L1b_Slice[2].L1_carry_in_a0 ;
  assign _0_ = \L1_Slice[1].L1_in1_a0  + \L1_Slice[1].L1_in2_a0 ;
  assign _1_ = _0_ + \L1b_Slice[1].L1_carry_in_a0 ;
  assign \L1b_Slice[2].L1_carry_in_a0  = _1_ > 2'h1;
endmodule

module fa_2(\L1_Slice[2].L1_in1_a0 , \L1_Slice[2].L1_in2_a0 , \L1b_Slice[2].L1_carry_in_a0 , \L1b_Slice[3].L1_carry_in_a0 );
  wire [1:0] _0_;
  wire [1:0] _1_;
  input \L1_Slice[2].L1_in1_a0 ;
  wire \L1_Slice[2].L1_in1_a0 ;
  input \L1_Slice[2].L1_in2_a0 ;
  wire \L1_Slice[2].L1_in2_a0 ;
  input \L1b_Slice[2].L1_carry_in_a0 ;
  wire \L1b_Slice[2].L1_carry_in_a0 ;
  output \L1b_Slice[3].L1_carry_in_a0 ;
  wire \L1b_Slice[3].L1_carry_in_a0 ;
  assign _0_ = \L1_Slice[2].L1_in1_a0  + \L1_Slice[2].L1_in2_a0 ;
  assign _1_ = _0_ + \L1b_Slice[2].L1_carry_in_a0 ;
  assign \L1b_Slice[3].L1_carry_in_a0  = _1_ > 2'h1;
endmodule

module fa_3(\L1_Slice[3].L1_in1_a0 , \L1_Slice[3].L1_in2_a0 , \L1b_Slice[3].L1_carry_in_a0 , \L1b_Slice[4].L1_carry_in_a0 );
  wire [1:0] _0_;
  wire [1:0] _1_;
  input \L1_Slice[3].L1_in1_a0 ;
  wire \L1_Slice[3].L1_in1_a0 ;
  input \L1_Slice[3].L1_in2_a0 ;
  wire \L1_Slice[3].L1_in2_a0 ;
  input \L1b_Slice[3].L1_carry_in_a0 ;
  wire \L1b_Slice[3].L1_carry_in_a0 ;
  output \L1b_Slice[4].L1_carry_in_a0 ;
  wire \L1b_Slice[4].L1_carry_in_a0 ;
  assign _0_ = \L1_Slice[3].L1_in1_a0  + \L1_Slice[3].L1_in2_a0 ;
  assign _1_ = _0_ + \L1b_Slice[3].L1_carry_in_a0 ;
  assign \L1b_Slice[4].L1_carry_in_a0  = _1_ > 2'h1;
endmodule

module fa_4(\L1_Slice[4].L1_in1_a0 , \L1_Slice[4].L1_in2_a0 , \L1b_Slice[4].L1_carry_in_a0 , \L1b_Slice[5].L1_carry_in_a0 );
  wire [1:0] _0_;
  wire [1:0] _1_;
  input \L1_Slice[4].L1_in1_a0 ;
  wire \L1_Slice[4].L1_in1_a0 ;
  input \L1_Slice[4].L1_in2_a0 ;
  wire \L1_Slice[4].L1_in2_a0 ;
  input \L1b_Slice[4].L1_carry_in_a0 ;
  wire \L1b_Slice[4].L1_carry_in_a0 ;
  output \L1b_Slice[5].L1_carry_in_a0 ;
  wire \L1b_Slice[5].L1_carry_in_a0 ;
  assign _0_ = \L1_Slice[4].L1_in1_a0  + \L1_Slice[4].L1_in2_a0 ;
  assign _1_ = _0_ + \L1b_Slice[4].L1_carry_in_a0 ;
  assign \L1b_Slice[5].L1_carry_in_a0  = _1_ > 2'h1;
endmodule

module fa_5(\L1_Slice[5].L1_in1_a0 , \L1_Slice[5].L1_in2_a0 , \L1b_Slice[5].L1_carry_in_a0 , \L1b_Slice[6].L1_carry_in_a0 );
  wire [1:0] _0_;
  wire [1:0] _1_;
  input \L1_Slice[5].L1_in1_a0 ;
  wire \L1_Slice[5].L1_in1_a0 ;
  input \L1_Slice[5].L1_in2_a0 ;
  wire \L1_Slice[5].L1_in2_a0 ;
  input \L1b_Slice[5].L1_carry_in_a0 ;
  wire \L1b_Slice[5].L1_carry_in_a0 ;
  output \L1b_Slice[6].L1_carry_in_a0 ;
  wire \L1b_Slice[6].L1_carry_in_a0 ;
  assign _0_ = \L1_Slice[5].L1_in1_a0  + \L1_Slice[5].L1_in2_a0 ;
  assign _1_ = _0_ + \L1b_Slice[5].L1_carry_in_a0 ;
  assign \L1b_Slice[6].L1_carry_in_a0  = _1_ > 2'h1;
endmodule

module fa_6(\L1_Slice[6].L1_in1_a0 , \L1_Slice[6].L1_in2_a0 , \L1b_Slice[6].L1_carry_in_a0 , \L1b_Slice[7].L1_carry_in_a0 );
  wire [1:0] _0_;
  wire [1:0] _1_;
  input \L1_Slice[6].L1_in1_a0 ;
  wire \L1_Slice[6].L1_in1_a0 ;
  input \L1_Slice[6].L1_in2_a0 ;
  wire \L1_Slice[6].L1_in2_a0 ;
  input \L1b_Slice[6].L1_carry_in_a0 ;
  wire \L1b_Slice[6].L1_carry_in_a0 ;
  output \L1b_Slice[7].L1_carry_in_a0 ;
  wire \L1b_Slice[7].L1_carry_in_a0 ;
  assign _0_ = \L1_Slice[6].L1_in1_a0  + \L1_Slice[6].L1_in2_a0 ;
  assign _1_ = _0_ + \L1b_Slice[6].L1_carry_in_a0 ;
  assign \L1b_Slice[7].L1_carry_in_a0  = _1_ > 2'h1;
endmodule

module fa_7(\L1_Slice[7].L1_in1_a0 , \L1_Slice[7].L1_in2_a0 , \L1b_Slice[7].L1_carry_in_a0 );
  wire [1:0] _0_;
  wire [1:0] _1_;
  input \L1_Slice[7].L1_in1_a0 ;
  wire \L1_Slice[7].L1_in1_a0 ;
  input \L1_Slice[7].L1_in2_a0 ;
  wire \L1_Slice[7].L1_in2_a0 ;
  input \L1b_Slice[7].L1_carry_in_a0 ;
  wire \L1b_Slice[7].L1_carry_in_a0 ;
  wire \Slice_carry_out_a0[7] ;
  assign _0_ = \L1_Slice[7].L1_in1_a0  + \L1_Slice[7].L1_in2_a0 ;
  assign _1_ = _0_ + \L1b_Slice[7].L1_carry_in_a0 ;
  assign \Slice_carry_out_a0[7]  = _1_ > 2'h1;
endmodule

module top(clk, reset, cyc_cnt, passed, failed);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [1:0] _08_;
  wire [1:0] _09_;
  wire [1:0] _10_;
  wire [1:0] _11_;
  wire [1:0] _12_;
  wire [1:0] _13_;
  wire [1:0] _14_;
  wire [1:0] _15_;
  wire [1:0] _16_;
  wire [1:0] _17_;
  wire [1:0] _18_;
  wire [1:0] _19_;
  wire [1:0] _20_;
  wire [1:0] _21_;
  wire [1:0] _22_;
  wire [1:0] _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire [7:0] L0_addend1_a0;
  wire [7:0] L0_addend2_a0;
  wire [8:0] L0_result_a0;
  wire \L1_Slice[0].L1_in1_a0 ;
  wire \L1_Slice[0].L1_in2_a0 ;
  wire \L1_Slice[1].L1_in1_a0 ;
  wire \L1_Slice[1].L1_in2_a0 ;
  wire \L1_Slice[2].L1_in1_a0 ;
  wire \L1_Slice[2].L1_in2_a0 ;
  wire \L1_Slice[3].L1_in1_a0 ;
  wire \L1_Slice[3].L1_in2_a0 ;
  wire \L1_Slice[4].L1_in1_a0 ;
  wire \L1_Slice[4].L1_in2_a0 ;
  wire \L1_Slice[5].L1_in1_a0 ;
  wire \L1_Slice[5].L1_in2_a0 ;
  wire \L1_Slice[6].L1_in1_a0 ;
  wire \L1_Slice[6].L1_in2_a0 ;
  wire \L1_Slice[7].L1_in1_a0 ;
  wire \L1_Slice[7].L1_in2_a0 ;
  wire \L1b_Slice[0].L1_carry_in_a0 ;
  wire \L1b_Slice[1].L1_carry_in_a0 ;
  wire \L1b_Slice[2].L1_carry_in_a0 ;
  wire \L1b_Slice[3].L1_carry_in_a0 ;
  wire \L1b_Slice[4].L1_carry_in_a0 ;
  wire \L1b_Slice[5].L1_carry_in_a0 ;
  wire \L1b_Slice[6].L1_carry_in_a0 ;
  wire \L1b_Slice[7].L1_carry_in_a0 ;
  wire [256:0] RW_rand_raw;
  wire [319:0] RW_rand_vect;
  wire \Slice_carry_out_a0[0] ;
  wire \Slice_carry_out_a0[1] ;
  wire \Slice_carry_out_a0[2] ;
  wire \Slice_carry_out_a0[3] ;
  wire \Slice_carry_out_a0[4] ;
  wire \Slice_carry_out_a0[5] ;
  wire \Slice_carry_out_a0[6] ;
  wire \Slice_carry_out_a0[7] ;
  wire [7:0] Slice_out_a0;
  input clk;
  wire clk;
  input [31:0] cyc_cnt;
  wire [31:0] cyc_cnt;
  output failed;
  wire failed;
  output passed;
  wire passed;
  input reset;
  wire reset;
  assign L0_result_a0[0] = \L1_Slice[0].L1_in1_a0  ^ \L1_Slice[0].L1_in2_a0 ;
  assign L0_result_a0[4] = _47_ ^ \L1b_Slice[4].L1_carry_in_a0 ;
  assign _33_ = \L1_Slice[5].L1_in1_a0  ^ \L1_Slice[5].L1_in2_a0 ;
  assign L0_result_a0[5] = _33_ ^ \L1b_Slice[5].L1_carry_in_a0 ;
  assign _35_ = \L1_Slice[6].L1_in1_a0  ^ \L1_Slice[6].L1_in2_a0 ;
  assign L0_result_a0[6] = _35_ ^ \L1b_Slice[6].L1_carry_in_a0 ;
  assign _37_ = \L1_Slice[7].L1_in1_a0  ^ \L1_Slice[7].L1_in2_a0 ;
  assign L0_result_a0[7] = _37_ ^ \L1b_Slice[7].L1_carry_in_a0 ;
  assign _41_ = \L1_Slice[1].L1_in1_a0  ^ \L1_Slice[1].L1_in2_a0 ;
  assign L0_result_a0[1] = _41_ ^ \L1b_Slice[1].L1_carry_in_a0 ;
  assign _43_ = \L1_Slice[2].L1_in1_a0  ^ \L1_Slice[2].L1_in2_a0 ;
  assign L0_result_a0[2] = _43_ ^ \L1b_Slice[2].L1_carry_in_a0 ;
  assign _45_ = \L1_Slice[3].L1_in1_a0  ^ \L1_Slice[3].L1_in2_a0 ;
  assign L0_result_a0[3] = _45_ ^ \L1b_Slice[3].L1_carry_in_a0 ;
  assign _47_ = \L1_Slice[4].L1_in1_a0  ^ \L1_Slice[4].L1_in2_a0 ;
  fa_0 fa_0 (
    .\L1_Slice[0].L1_in1_a0 (\L1_Slice[0].L1_in1_a0 ),
    .\L1_Slice[0].L1_in2_a0 (\L1_Slice[0].L1_in2_a0 ),
    .\L1b_Slice[1].L1_carry_in_a0 (\L1b_Slice[1].L1_carry_in_a0 )
  );
  fa_1 fa_1 (
    .\L1_Slice[1].L1_in1_a0 (\L1_Slice[1].L1_in1_a0 ),
    .\L1_Slice[1].L1_in2_a0 (\L1_Slice[1].L1_in2_a0 ),
    .\L1b_Slice[1].L1_carry_in_a0 (\L1b_Slice[1].L1_carry_in_a0 ),
    .\L1b_Slice[2].L1_carry_in_a0 (\L1b_Slice[2].L1_carry_in_a0 )
  );
  fa_2 fa_2 (
    .\L1_Slice[2].L1_in1_a0 (\L1_Slice[2].L1_in1_a0 ),
    .\L1_Slice[2].L1_in2_a0 (\L1_Slice[2].L1_in2_a0 ),
    .\L1b_Slice[2].L1_carry_in_a0 (\L1b_Slice[2].L1_carry_in_a0 ),
    .\L1b_Slice[3].L1_carry_in_a0 (\L1b_Slice[3].L1_carry_in_a0 )
  );
  fa_3 fa_3 (
    .\L1_Slice[3].L1_in1_a0 (\L1_Slice[3].L1_in1_a0 ),
    .\L1_Slice[3].L1_in2_a0 (\L1_Slice[3].L1_in2_a0 ),
    .\L1b_Slice[3].L1_carry_in_a0 (\L1b_Slice[3].L1_carry_in_a0 ),
    .\L1b_Slice[4].L1_carry_in_a0 (\L1b_Slice[4].L1_carry_in_a0 )
  );
  fa_4 fa_4 (
    .\L1_Slice[4].L1_in1_a0 (\L1_Slice[4].L1_in1_a0 ),
    .\L1_Slice[4].L1_in2_a0 (\L1_Slice[4].L1_in2_a0 ),
    .\L1b_Slice[4].L1_carry_in_a0 (\L1b_Slice[4].L1_carry_in_a0 ),
    .\L1b_Slice[5].L1_carry_in_a0 (\L1b_Slice[5].L1_carry_in_a0 )
  );
  fa_5 fa_5 (
    .\L1_Slice[5].L1_in1_a0 (\L1_Slice[5].L1_in1_a0 ),
    .\L1_Slice[5].L1_in2_a0 (\L1_Slice[5].L1_in2_a0 ),
    .\L1b_Slice[5].L1_carry_in_a0 (\L1b_Slice[5].L1_carry_in_a0 ),
    .\L1b_Slice[6].L1_carry_in_a0 (\L1b_Slice[6].L1_carry_in_a0 )
  );
  fa_6 fa_6 (
    .\L1_Slice[6].L1_in1_a0 (\L1_Slice[6].L1_in1_a0 ),
    .\L1_Slice[6].L1_in2_a0 (\L1_Slice[6].L1_in2_a0 ),
    .\L1b_Slice[6].L1_carry_in_a0 (\L1b_Slice[6].L1_carry_in_a0 ),
    .\L1b_Slice[7].L1_carry_in_a0 (\L1b_Slice[7].L1_carry_in_a0 )
  );
  fa_7 fa_7 (
    .\L1_Slice[7].L1_in1_a0 (\L1_Slice[7].L1_in1_a0 ),
    .\L1_Slice[7].L1_in2_a0 (\L1_Slice[7].L1_in2_a0 ),
    .\L1b_Slice[7].L1_carry_in_a0 (\L1b_Slice[7].L1_carry_in_a0 )
  );
  pseudo_rand #(
    .WIDTH(32'sd257)
  ) pseudo_rand (
    clk,
    reset,
    { RW_rand_raw[256:132], \L1_Slice[7].L1_in2_a0 , \L1_Slice[6].L1_in2_a0 , \L1_Slice[5].L1_in2_a0 , \L1_Slice[4].L1_in2_a0 , \L1_Slice[3].L1_in2_a0 , \L1_Slice[2].L1_in2_a0 , \L1_Slice[1].L1_in2_a0 , \L1_Slice[0].L1_in2_a0 , RW_rand_raw[123:8], \L1_Slice[7].L1_in1_a0 , \L1_Slice[6].L1_in1_a0 , \L1_Slice[5].L1_in1_a0 , \L1_Slice[4].L1_in1_a0 , \L1_Slice[3].L1_in1_a0 , \L1_Slice[2].L1_in1_a0 , \L1_Slice[1].L1_in1_a0 , \L1_Slice[0].L1_in1_a0  }
  );
  assign _00_ = \L1b_Slice[1].L1_carry_in_a0 ;
  assign _01_ = \L1b_Slice[2].L1_carry_in_a0 ;
  assign _02_ = \L1b_Slice[3].L1_carry_in_a0 ;
  assign _03_ = \L1b_Slice[4].L1_carry_in_a0 ;
  assign _04_ = \L1b_Slice[5].L1_carry_in_a0 ;
  assign _05_ = \L1b_Slice[6].L1_carry_in_a0 ;
  assign _06_ = \L1b_Slice[7].L1_carry_in_a0 ;
  assign _07_ = L0_result_a0[8];
  assign _24_ = \L1b_Slice[1].L1_carry_in_a0 ;
  assign _25_ = \L1b_Slice[2].L1_carry_in_a0 ;
  assign _26_ = \L1b_Slice[3].L1_carry_in_a0 ;
  assign _27_ = \L1b_Slice[4].L1_carry_in_a0 ;
  assign _28_ = \L1b_Slice[5].L1_carry_in_a0 ;
  assign _29_ = \L1b_Slice[6].L1_carry_in_a0 ;
  assign _30_ = \L1b_Slice[7].L1_carry_in_a0 ;
  assign _31_ = L0_result_a0[8];
  assign _32_ = L0_result_a0[4];
  assign _34_ = L0_result_a0[5];
  assign _36_ = L0_result_a0[6];
  assign _38_ = L0_result_a0[7];
  assign _39_ = L0_result_a0[0];
  assign _40_ = L0_result_a0[0];
  assign _42_ = L0_result_a0[1];
  assign _44_ = L0_result_a0[2];
  assign _46_ = L0_result_a0[3];
  assign L0_addend1_a0 = { \L1_Slice[7].L1_in1_a0 , \L1_Slice[6].L1_in1_a0 , \L1_Slice[5].L1_in1_a0 , \L1_Slice[4].L1_in1_a0 , \L1_Slice[3].L1_in1_a0 , \L1_Slice[2].L1_in1_a0 , \L1_Slice[1].L1_in1_a0 , \L1_Slice[0].L1_in1_a0  };
  assign L0_addend2_a0 = { \L1_Slice[7].L1_in2_a0 , \L1_Slice[6].L1_in2_a0 , \L1_Slice[5].L1_in2_a0 , \L1_Slice[4].L1_in2_a0 , \L1_Slice[3].L1_in2_a0 , \L1_Slice[2].L1_in2_a0 , \L1_Slice[1].L1_in2_a0 , \L1_Slice[0].L1_in2_a0  };
  assign \L1b_Slice[0].L1_carry_in_a0  = 1'h0;
  assign { RW_rand_raw[131:124], RW_rand_raw[7:0] } = { \L1_Slice[7].L1_in2_a0 , \L1_Slice[6].L1_in2_a0 , \L1_Slice[5].L1_in2_a0 , \L1_Slice[4].L1_in2_a0 , \L1_Slice[3].L1_in2_a0 , \L1_Slice[2].L1_in2_a0 , \L1_Slice[1].L1_in2_a0 , \L1_Slice[0].L1_in2_a0 , \L1_Slice[7].L1_in1_a0 , \L1_Slice[6].L1_in1_a0 , \L1_Slice[5].L1_in1_a0 , \L1_Slice[4].L1_in1_a0 , \L1_Slice[3].L1_in1_a0 , \L1_Slice[2].L1_in1_a0 , \L1_Slice[1].L1_in1_a0 , \L1_Slice[0].L1_in1_a0  };
  assign RW_rand_vect = { RW_rand_raw[62:8], \L1_Slice[7].L1_in1_a0 , \L1_Slice[6].L1_in1_a0 , \L1_Slice[5].L1_in1_a0 , \L1_Slice[4].L1_in1_a0 , \L1_Slice[3].L1_in1_a0 , \L1_Slice[2].L1_in1_a0 , \L1_Slice[1].L1_in1_a0 , \L1_Slice[0].L1_in1_a0 , RW_rand_raw[256:132], \L1_Slice[7].L1_in2_a0 , \L1_Slice[6].L1_in2_a0 , \L1_Slice[5].L1_in2_a0 , \L1_Slice[4].L1_in2_a0 , \L1_Slice[3].L1_in2_a0 , \L1_Slice[2].L1_in2_a0 , \L1_Slice[1].L1_in2_a0 , \L1_Slice[0].L1_in2_a0 , RW_rand_raw[123:8], \L1_Slice[7].L1_in1_a0 , \L1_Slice[6].L1_in1_a0 , \L1_Slice[5].L1_in1_a0 , \L1_Slice[4].L1_in1_a0 , \L1_Slice[3].L1_in1_a0 , \L1_Slice[2].L1_in1_a0 , \L1_Slice[1].L1_in1_a0 , \L1_Slice[0].L1_in1_a0  };
  assign \Slice_carry_out_a0[0]  = \L1b_Slice[1].L1_carry_in_a0 ;
  assign \Slice_carry_out_a0[1]  = \L1b_Slice[2].L1_carry_in_a0 ;
  assign \Slice_carry_out_a0[2]  = \L1b_Slice[3].L1_carry_in_a0 ;
  assign \Slice_carry_out_a0[3]  = \L1b_Slice[4].L1_carry_in_a0 ;
  assign \Slice_carry_out_a0[4]  = \L1b_Slice[5].L1_carry_in_a0 ;
  assign \Slice_carry_out_a0[5]  = \L1b_Slice[6].L1_carry_in_a0 ;
  assign \Slice_carry_out_a0[6]  = \L1b_Slice[7].L1_carry_in_a0 ;
  assign \Slice_carry_out_a0[7]  = L0_result_a0[8];
  assign Slice_out_a0 = L0_result_a0[7:0];
endmodule
